### ISSUE TITLE
When I process recorded xef files using ex-capture gives me below error

### ISSUE THREAD

**Issue by arm235** [Qirky/PyKinectTk#9]
Listening for Kinect data
Hover over the location you want to click and press enter
Traceback (most recent call last):
  File "ex-capture.py", line 21, in <module>
    App.listen(getVideo=True, Clicking=True, duration=120)
  File "C:\Users\741467\.conda\envs\py2\lib\site-packages\PyKinectTk\Capture\DataCapture.py", line 213, in listen
    body_frame = self.get_body_frame()
  File "C:\Users\741467\.conda\envs\py2\lib\site-packages\PyKinectTk\Capture\DataCapture.py", line 137, in get_body_frame
    return self._kinect.get_last_body_frame()
  File "C:\Users\741467\.conda\envs\py2\lib\site-packages\PyKinectTk\utils\PyKinect2\PyKinectRuntime.py", line 280, in get_last_body_frame
    return self._body_frame_bodies.copy()
  File "C:\Users\741467\.conda\envs\py2\lib\site-packages\PyKinectTk\utils\PyKinect2\PyKinectRuntime.py", line 547, in copy
    res.floor_clip_plane = self.floor_clip_plane
KeyboardInterrupt

**Comment by Qirky** [comment]
Hi there, I don't work on this project any more and won't be able to give you any detailed responses but a KeyboardInterrupt error usually occurs when you press Ctrl+C so that's a bit strange

**Comment by arm235** [comment]
It reads kinect data when I press step key but does not stop automatically. Also generate one output avi file which does not open up.  It was not giving any results, so I pressed key. It shows receiving data done and gives error.

**Comment by arm235** [comment]
I have pressed keyboard ctrl+ c key so that error came. Actually it keeps reading kinect data repeatedly. And does not stop so pressed keys. And even though does not drop images or any data after this. Your help will be highly appreciated.
